apiVersion: v1
kind: Secret
metadata:
  name: messenger-secrets
  namespace: messenger
  labels:
    app.kubernetes.io/name: messenger-secrets
    app.kubernetes.io/part-of: messenger-backend
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change-me"
  RABBITMQ_USER: "root"
  RABBITMQ_PASSWORD: "change-me"
  MONGODB_USER: "user"
  MONGODB_PASSWORD: "change-me"
  JWT_SECRET: "change-me"
  SESSION_SECRET: "change-me"
